### ISSUE TITLE
Add support for access tokens in the container's environment variables

### ISSUE THREAD

**Issue by christinaexyou** [trustyai-explainability/llama-stack-provider-lmeval#6]
Update `create_pod_config` to reference tokens from K8s `Secret` resources in the container's environment variables, eg.:

```
apiVersion: trustyai.opendatahub.io/v1alpha1
kind: LMEvalJob
metadata:
  name: evaljob
spec:
  model: local-completions
  taskList:
    taskNames:
      - mmlu
  logSamples: true
  batchSize: 1
  modelArgs:
    - name: model
      value: granite
    - name: base_url
      value: $ROUTE_TO_MODEL/v1/completions
    - name: num_concurrent
      value:  "1"
    - name: max_retries
      value:  "3"
    - name: tokenized_requests
      value: "False"
    - name: tokenizer
      value: ibm-granite/granite-7b-instruct
  pod:
    container:
      env:
       - name: OPENAI_API_KEY
         valueFrom:
              secretKeyRef:
                name: <secret-name>
                key: token
```
